services:
    web:
        container_name: web
        build:
            context: ../../../
            dockerfile: deployments/docker/dev/Dockerfile.dev
        image: web:latest
        environment:
            CHDIR: /app
        restart: always
        volumes:
            - ../../../:/app
        ports:
            - '5031:8000'
        depends_on:
            - web-db

    web-db:
        image: postgres:16-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: django
            POSTGRES_USER: root
            POSTGRES_PASSWORD: stringPass123
        ports:
            - '5432:5432'

volumes:
    postgres_data:
